language:
  - node_js
  - version: 8

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - nvm install --lts
  - nvm use 'lts/*'
  - npm i -g yarn
  - nvm --version
  - npm --version
  - node --version
  - yarn --version
  - yarn

script:
  - yarn lint
  - yarn nyc

after_success:
  # chmod u+rwx, chmod og+rx
  - chmod 755 /Users/travis/build/l3laze/node-steam-config/.nyc_output
  - yarn textcov
  - yarn codecov && yarn codacy

notifications:
  email: false
