language: node_js

node_js: "lts/*"

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - chmod u+x travis_fold.sh
  - sh travis_fold.sh start YARN
  - npm i -g yarn
  - sh travis_fold.sh end

script:
  - sh travis_fold.sh start SCRIPT
  - yarn lint
  - chmod u+x perms.sh
  - sh perms.sh script
  - sh travis_fold.sh end
  - sh travis_fold.sh start TESTING
  - yarn nyc
  - sh travis_fold.sh end
  - sh travis_fold.sh start AFTER_SCRIPT
  - sh perms.sh after
  - sh travis_fold.sh end

after_success:
  - sh travis_fold.sh start COVERAGE
  - yarn textcov
  - yarn codecov && yarn codacy
  - sh travis_fold.sh end

notifications:
  email: false
