language:
  - node_js
  - version: 8

os:
  - osx

cache:
  yarn: true

before_install:
  - nvm install --lts
  - nvm use 'lts/*'
  - npm i -g yarn
  - nvm --version
  - npm --version
  - node --version
  - yarn --version
  - yarn

script:
  - yarn lint
  - yarn test

after_success:
  - chmod 0755 .nyc_output
  - yarn run coverage
