language: node_js

node_js: "lts/*"

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - npm i -g yarn

script:
  - echo -en "travis_fold:start:SCRIPT\r"
  - yarn lint
  - yarn nyc
  - echo -en "travis_fold:end:SCRIPT\r"

after_success:
  - echo -en "travis_fold:start:COVERAGE\r"
  - chmod 755 /Users/travis/build/l3laze/node-steam-config/.nyc_output
  - yarn textcov
  - yarn codecov && yarn codacy
  - echo -en "travis_fold:end:COVERAGE\r"

notifications:
  email: false
