language:
  - node_js
  - version: 8

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
    - home/travis/build/l3laze/node-steam-config/node_modules
    - Users/travis/build/l3laze/node-steam-config/node_modules

before_install:
  - nvm install --lts
  - npm i -g yarn

script:
  - yarn lint
  - chmod u+x perms.sh
  - sh perms.sh script
  - yarn nyc

after_success:
  - sh perms.sh after
  - yarn textcov
  - yarn codecov && yarn codacy

notifications:
  email: false
